BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "room_members" (
	"room"	TEXT NOT NULL,
	"user"	INTEGER NOT NULL UNIQUE,
	"redirection_key"	INTEGER NOT NULL UNIQUE,
	FOREIGN KEY("room") REFERENCES "rooms"("id"),
	PRIMARY KEY("user")
);
COMMIT;