BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "rooms" (
	"id"	TEXT NOT NULL UNIQUE,
	"code"	INTEGER NOT NULL UNIQUE,
	"admin"	TEXT NOT NULL,
	"is_game"	INTEGER NOT NULL,
	"game"	TEXT,
	PRIMARY KEY("id"),
	FOREIGN KEY("admin") REFERENCES "users"("id")
);
COMMIT;